### ISSUE TITLE
Question: Could I get the resulting price through a backend API?

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/PriceCalculation#1]
Let's say I create salesorders through a custom module I built and I want the lines to take the price modifications this module offers into account. Could I feed the lines into an API this module offers so that I get the same result as when I would be doing it on the frontend?

**Comment by joebordes** [comment]
Yes, absolutely. One of these two methods should give you the numbers you are looking for:

https://github.com/tsolucio/PriceCalculation/blob/master/modules/DiscountLine/DiscountLine.php#L264

https://github.com/tsolucio/PriceCalculation/blob/master/modules/DiscountLine/DiscountLine.php#L390

**Comment by Luke1982** [comment]
Very nice!
