### ISSUE TITLE
Changing back to a 0-discount account does not reset the discount on the line

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/PriceCalculation#4]
Say you are composing a SalesOrder for account A, that has a 20% discount on all products. Selecting a product from the autocomplete will use that 20% discount. Now you change the account capture field to a customer that has no discount. That won't reset the discount back to 0.

**Comment by joebordes** [comment]
[this commit](https://github.com/tsolucio/corebos/commit/e6d3bd5dcea942ca943ddc1c505deebfb02d590e) should fix this issue hopefully without breaking anything.
