### ISSUE TITLE
Selecting a new product won't bring back discount to zero

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/PriceCalculation#6]
Let's say you have a product that you have awarded a 20% discount. You select it through the autocomplete, then you use the same autocomplete on the same line to select a different product, one that you have not awarded any discount. That will not reset the discount value back to 0 on the line.

**Comment by joebordes** [comment]
[this commit](https://github.com/tsolucio/corebos/commit/e6d3bd5dcea942ca943ddc1c505deebfb02d590e) should fix this issue hopefully without breaking anything.
